/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Mogith
 */
public class booking extends javax.swing.JFrame {
int n=0;
    /**
     * Creates new form booking
     */
    public booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        ncar6 = new javax.swing.JLabel();
        ncar1 = new javax.swing.JLabel();
        ncar7 = new javax.swing.JLabel();
        ncar3 = new javax.swing.JLabel();
        ncar4 = new javax.swing.JLabel();
        ncar9 = new javax.swing.JLabel();
        ncar2 = new javax.swing.JLabel();
        ncar8 = new javax.swing.JLabel();
        car4 = new javax.swing.JLabel();
        ncar5 = new javax.swing.JLabel();
        ncar10 = new javax.swing.JLabel();
        ncar15 = new javax.swing.JLabel();
        ncar14 = new javax.swing.JLabel();
        ncar13 = new javax.swing.JLabel();
        ncar12 = new javax.swing.JLabel();
        ncar11 = new javax.swing.JLabel();
        car1 = new javax.swing.JLabel();
        car2 = new javax.swing.JLabel();
        car6 = new javax.swing.JLabel();
        car5 = new javax.swing.JLabel();
        cnfslot = new javax.swing.JButton();
        back = new javax.swing.JButton();
        car3 = new javax.swing.JLabel();
        car7 = new javax.swing.JLabel();
        car9 = new javax.swing.JLabel();
        car8 = new javax.swing.JLabel();
        car10 = new javax.swing.JLabel();
        car11 = new javax.swing.JLabel();
        car12 = new javax.swing.JLabel();
        car13 = new javax.swing.JLabel();
        car14 = new javax.swing.JLabel();
        car15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        carnumb = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ncar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar6MouseClicked(evt);
            }
        });
        getContentPane().add(ncar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 60));

        ncar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar1MouseClicked(evt);
            }
        });
        getContentPane().add(ncar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 50, 90));

        ncar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar7MouseClicked(evt);
            }
        });
        getContentPane().add(ncar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 60));

        ncar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar3MouseClicked(evt);
            }
        });
        getContentPane().add(ncar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, 60));

        ncar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar4MouseClicked(evt);
            }
        });
        getContentPane().add(ncar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 87));

        ncar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar9MouseClicked(evt);
            }
        });
        getContentPane().add(ncar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 60));

        ncar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar2MouseClicked(evt);
            }
        });
        getContentPane().add(ncar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, 80));

        ncar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar8MouseClicked(evt);
            }
        });
        getContentPane().add(ncar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, 60));

        car4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car4MouseClicked(evt);
            }
        });
        getContentPane().add(car4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 70));

        ncar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar5MouseClicked(evt);
            }
        });
        getContentPane().add(ncar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, 60));

        ncar10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar10MouseClicked(evt);
            }
        });
        getContentPane().add(ncar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, 60));

        ncar15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar15MouseClicked(evt);
            }
        });
        getContentPane().add(ncar15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, 70));

        ncar14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar14MouseClicked(evt);
            }
        });
        getContentPane().add(ncar14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, 60));

        ncar13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar13MouseClicked(evt);
            }
        });
        getContentPane().add(ncar13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, 70));

        ncar12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar12MouseClicked(evt);
            }
        });
        getContentPane().add(ncar12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, 70));

        ncar11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/1.11.png"))); // NOI18N
        ncar11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncar11MouseClicked(evt);
            }
        });
        getContentPane().add(ncar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 60));

        car1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                car1MouseEntered(evt);
            }
        });
        getContentPane().add(car1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 50, 70));

        car2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car2MouseClicked(evt);
            }
        });
        getContentPane().add(car2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, 60));

        car6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car6MouseClicked(evt);
            }
        });
        getContentPane().add(car6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 70));

        car5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car5MouseClicked(evt);
            }
        });
        getContentPane().add(car5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 70));

        cnfslot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cnfslot.setText("CONFIRM SLOT");
        cnfslot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnfslotActionPerformed(evt);
            }
        });
        getContentPane().add(cnfslot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        car3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car3MouseClicked(evt);
            }
        });
        getContentPane().add(car3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, 70));

        car7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car7MouseClicked(evt);
            }
        });
        getContentPane().add(car7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 70));

        car9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car9MouseClicked(evt);
            }
        });
        getContentPane().add(car9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 70));

        car8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car8MouseClicked(evt);
            }
        });
        getContentPane().add(car8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, 70));

        car10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car10MouseClicked(evt);
            }
        });
        getContentPane().add(car10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, 70));

        car11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car11MouseClicked(evt);
            }
        });
        getContentPane().add(car11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 70));

        car12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car12MouseClicked(evt);
            }
        });
        getContentPane().add(car12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, 70));

        car13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car13MouseClicked(evt);
            }
        });
        getContentPane().add(car13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, 70));

        car14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car14MouseClicked(evt);
            }
        });
        getContentPane().add(car14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, 70));

        car15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/2.22.png"))); // NOI18N
        car15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car15MouseClicked(evt);
            }
        });
        getContentPane().add(car15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, 70));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHECKOUT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 100, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CHECKIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 70, -1));

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 140, -1));

        jDateChooser3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser3MouseClicked(evt);
            }
        });
        getContentPane().add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 150, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 153, 102));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 440, 290));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 770, 90));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 40, 290));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Carnumber");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 70, 30));

        carnumb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carnumbActionPerformed(evt);
            }
        });
        getContentPane().add(carnumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 120, 30));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 290, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 static String selected = null;
    private void ncar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar1MouseClicked
        // TODO add your handling code here:
        selected = "scar1";
         ncar1.setVisible(false);
        car1.setVisible(true);
    }//GEN-LAST:event_ncar1MouseClicked

    private void car1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car1MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                String sel = "scar1";
                System.out.println(s);
       if(sel.equalsIgnoreCase(s)){
                   System.out.println("h"+s);
             ncar1.setVisible(false);
          car1.setVisible(true);
            }
              else
              {
                 ncar1.setVisible(true);
          car1.setVisible(false); 
              }
            }
         }
            catch(Exception e){
                    e.printStackTrace();
                    }
    }//GEN-LAST:event_car1MouseClicked

    private void cnfslotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnfslotActionPerformed
        // TODO add your handling code here: 
     try{
         if (d>=1){
             JOptionPane op = new JOptionPane();
             op.showMessageDialog(null,"enter the checkin or check out  date:","",JOptionPane.ERROR_MESSAGE);
         }
         else{
             String query="insert into booking(username,carnumber,checkout,checkin,carnumbers) values(?,?,?,?,?) ";
        Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
       SimpleDateFormat dateFormat = new SimpleDataFormat("yyyy-mm-dd");
        String thedate= dateFormat.format(jDateChooser1.getDate());
        SimpleDateFormat dateFormats = new SimpleDataFormat("yyyy-mm-dd");
        String thedates= dateFormats.format(jDateChooser3.getDate()); 
        String m=thedate.substring(0, 9);
        String n=thedates.substring(0, 9);
        String a1 = reverse(m);
        String b1 = reverse(n);
        String b5=carnumb.getText();
             PreparedStatement ps= con.prepareStatement(query);
             ps.setString(1,loginpage.edtUsername.getText());
             ps.setString(2,selected);
             ps.setString(3, a1);
             ps.setString(4, b1);
             ps.setString(5, b5);
             ps.executeUpdate();
             String s = "select  DATEDIFF(checkout,checkin) from booking where username = '"+loginpage.edtUsername.getText()+"'";
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(s);
             String days="";
             if(rs.next()){
                 String a ="checkout";
                 String b ="checkin";
               days = rs.getString("DATEDIFF(checkout,checkin)");   
             }
            int day = Integer.parseInt(days);
        int cost,total=0;
        cost = 17000*(day / 365); total += 1250*(day / 365); day = (day % 365);
        cost += 1400*(day / 30); total += 100*(day / 30); day = (day % 30);
        cost += 300*(day / 7); total += 50*(day / 7); day = (day % 7);
        cost += 50*day;
              payment p = new payment();
              p.txtpay1.setText(String.valueOf(cost));
             p.setVisible(true);
             this.dispose();
             
             JOptionPane op1 = new JOptionPane();
             op1.showMessageDialog(null,"slot booked successfully  \n thanks for booking \n you will save RS."+total,"",JOptionPane.INFORMATION_MESSAGE);
         }
     }
     catch(Exception e){
         e.printStackTrace();
         System.out.println(e);
         
     }
    }//GEN-LAST:event_cnfslotActionPerformed
static String reverse(String m){
        char[] arr = new char[8];
        m.getChars(0,8,arr,0);
        char x1 = arr[6];
        char x2 = arr[7];
        arr[6] = arr[0]; arr[7] = arr[1]; arr[0] = 
        x1; arr[1] = x2;
        String a = new String(arr);
        return a;
    }
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        homepage p = new homepage();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void ncar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar2MouseClicked
        // TODO add your handling code here:
        ncar2.setVisible(false);
        car2.setVisible(true);
        selected = "scar2";
    }//GEN-LAST:event_ncar2MouseClicked

    private void car2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car2MouseClicked
        // TODO add your handling code here:
         try{
           String s = null;  
           String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while(rs.next()){
              s = rs.getString(2);
              String sel = "scar2";
               System.out.println(s);
              if(sel.equalsIgnoreCase(s)){
                   System.out.println("h"+s);
             ncar2.setVisible(false);
          car2.setVisible(true);
            }
              else
              {
                  System.out.println("else:"+s);
                 ncar2.setVisible(true);
          car2.setVisible(false); 
              }
            }
      }
         catch(Exception e){
            e.printStackTrace();
        }
         
        
    }//GEN-LAST:event_car2MouseClicked

    private void ncar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar3MouseClicked
        // TODO add your handling code here:
        ncar3.setVisible(false);
        car3.setVisible(true);
        selected = "scar3";
    }//GEN-LAST:event_ncar3MouseClicked

    private void car3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car3MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                 String sel = "scar3";
               if(sel.equalsIgnoreCase(s)){
             ncar3.setVisible(false);
          car3.setVisible(true);
            }
              else
              {
                 ncar3.setVisible(true);
          car3.setVisible(false); 
              }
        }
      }
        catch(Exception e){
            e.printStackTrace();
        }   
    }//GEN-LAST:event_car3MouseClicked

    private void ncar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar4MouseClicked
        // TODO add your handling code here:
        ncar4.setVisible(false);
        car4.setVisible(true);
        selected = "scar4";
    }//GEN-LAST:event_ncar4MouseClicked

    private void car4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car4MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{
             
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                 String sel;
          sel = "scar4";
               if(sel.equalsIgnoreCase(s)){
             ncar4.setVisible(false);
          car4.setVisible(true);
            }
              else
              {
                 ncar4.setVisible(true);
          car4.setVisible(false); 
              }
        }
      }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_car4MouseClicked

    private void ncar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar5MouseClicked
        // TODO add your handling code here:
        ncar5.setVisible(false);
        car5.setVisible(true);
        selected = "scar5";
    }//GEN-LAST:event_ncar5MouseClicked

    private void car5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car5MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                 String sel = "scar5";
               if(sel.equalsIgnoreCase(s)){
             ncar5.setVisible(false);
          car5.setVisible(true);
            }
              else
              {
                 ncar5.setVisible(true);
          car5.setVisible(false); 
              }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_car5MouseClicked

    private void ncar6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar6MouseClicked
        // TODO add your handling code here:
        ncar6.setVisible(false);
        car6.setVisible(true);
        selected = "scar6";
    }//GEN-LAST:event_ncar6MouseClicked

    private void car6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car6MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                 String sel = "scar6";
               if(sel.equalsIgnoreCase(s)){
             ncar6.setVisible(false);
          car6.setVisible(true);
            }
              else
              {
                 ncar6.setVisible(true);
          car6.setVisible(false); 
              }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_car6MouseClicked

    private void ncar7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar7MouseClicked
        // TODO add your handling code here:
        ncar7.setVisible(false);
        car7.setVisible(true);
        selected = "scar7";
    }//GEN-LAST:event_ncar7MouseClicked

    private void car7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car7MouseClicked
        // TODO add your handling code here:
         String s = null;
         try{
             
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                 String sel;
         sel = "scar7";
                  if(sel.equalsIgnoreCase(s)){
             ncar7.setVisible(false);
          car7.setVisible(true);
            }
              else
              {
                 ncar7.setVisible(true);
          car7.setVisible(false); 
              }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_car7MouseClicked

    private void ncar8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar8MouseClicked
        // TODO add your handling code here:
        ncar8.setVisible(false);
        car8.setVisible(true);
        selected = "scar8";
    }//GEN-LAST:event_ncar8MouseClicked

    private void car8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car8MouseClicked
        // TODO add your handling code here:
         String s = null;
         try{
             
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                 String sel;
                sel = "scar8";
               if(sel.equalsIgnoreCase(s)){
             ncar8.setVisible(false);
          car8.setVisible(true);
            }
              else
              {
                 ncar8.setVisible(true);
          car8.setVisible(false); 
              }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_car8MouseClicked

    private void ncar9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar9MouseClicked
        // TODO add your handling code here:
        ncar9.setVisible(false);
        car9.setVisible(true);
        selected = "scar9";
    }//GEN-LAST:event_ncar9MouseClicked

    private void car9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car9MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{      
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                  String sel;
        sel = "scar9";
               if(sel.equalsIgnoreCase(s)){
             ncar9.setVisible(false);
          car9.setVisible(true);
            }
              else
              {
                 ncar9.setVisible(true);
          car9.setVisible(false); 
              }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_car9MouseClicked

    private void ncar10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar10MouseClicked
        // TODO add your handling code here:
        ncar10.setVisible(false);
        car10.setVisible(true);
        selected = "scar10";
    }//GEN-LAST:event_ncar10MouseClicked

    private void car10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car10MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                  String sel;
            sel = "scar10";
              if(sel.equalsIgnoreCase(s)){
             ncar10.setVisible(false);
          car10.setVisible(true);
            }
              else
              {
                 ncar10.setVisible(true);
          car10.setVisible(false); 
              }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_car10MouseClicked

    private void ncar11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar11MouseClicked
        // TODO add your handling code here:
        ncar11.setVisible(false);
        car11.setVisible(true);
        selected = "scar11";
    }//GEN-LAST:event_ncar11MouseClicked

    private void car11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car11MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{
             
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
               s = rs.getString(2);
               String sel = "scar11";
               if(sel.equalsIgnoreCase(s))
               {
                    ncar11.setVisible(false);
                    car11.setVisible(true);
               }
               else
               {
                    ncar11.setVisible(true);
                    car11.setVisible(false); 
               }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_car11MouseClicked

    private void ncar12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar12MouseClicked
        // TODO add your handling code here:
        ncar12.setVisible(false);
        car12.setVisible(true);
        selected = "scar12";
    }//GEN-LAST:event_ncar12MouseClicked

    private void car12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car12MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                 String sel = "scar12";
               if(sel.equalsIgnoreCase(s)){
             ncar12.setVisible(false);
          car12.setVisible(true);
            }
              else
              {
                 ncar12.setVisible(true);
          car12.setVisible(false); 
              }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_car12MouseClicked

    private void ncar13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar13MouseClicked
        // TODO add your handling code here:
        ncar13.setVisible(false);
        car13.setVisible(true);
        selected = "scar13";
    }//GEN-LAST:event_ncar13MouseClicked

    private void car13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car13MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                 String sel = "scar13";
               if(sel.equalsIgnoreCase(s)){
             ncar13.setVisible(false);
          car13.setVisible(true);
            }
              else
              {
                 ncar13.setVisible(true);
          car13.setVisible(false); 
              }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_car13MouseClicked

    private void ncar14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar14MouseClicked
        // TODO add your handling code here:
        ncar14.setVisible(false);
        car14.setVisible(true);
        selected = "scar14";
    }//GEN-LAST:event_ncar14MouseClicked

    private void car14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car14MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                 String sel;
                 sel = "scar14";
               if(sel.equalsIgnoreCase(s)){
             ncar14.setVisible(false);
          car14.setVisible(true);
            }
              else
              {
                 ncar14.setVisible(true);
          car14.setVisible(false); 
              }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_car14MouseClicked

    private void ncar15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncar15MouseClicked
        // TODO add your handling code here:
        ncar15.setVisible(false);
        car15.setVisible(true);
        selected = "scar15";
    }//GEN-LAST:event_ncar15MouseClicked

    private void car15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car15MouseClicked
        // TODO add your handling code here:
        String s = null;
         try{
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 s = rs.getString(2);
                String sel = "scar15"; 
               if(sel.equalsIgnoreCase(s)){
             ncar15.setVisible(false);
          car15.setVisible(true);
            }
              else
              {
                 ncar15.setVisible(true);
          car15.setVisible(false); 
              }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_car15MouseClicked
int d=0;
    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:
        d++;
    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void jDateChooser3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser3MouseClicked
        // TODO add your handling code here:
        d++;
    }//GEN-LAST:event_jDateChooser3MouseClicked

    private void car1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_car1MouseEntered

    private void carnumbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carnumbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carnumbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    public static javax.swing.JLabel car1;
    public static javax.swing.JLabel car10;
    public static javax.swing.JLabel car11;
    public static javax.swing.JLabel car12;
    public static javax.swing.JLabel car13;
    public static javax.swing.JLabel car14;
    public static javax.swing.JLabel car15;
    public static javax.swing.JLabel car2;
    public static javax.swing.JLabel car3;
    public static javax.swing.JLabel car4;
    public static javax.swing.JLabel car5;
    public static javax.swing.JLabel car6;
    public static javax.swing.JLabel car7;
    public static javax.swing.JLabel car8;
    public static javax.swing.JLabel car9;
    private javax.swing.JTextField carnumb;
    private javax.swing.JButton cnfslot;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JLabel ncar1;
    public static javax.swing.JLabel ncar10;
    public static javax.swing.JLabel ncar11;
    public static javax.swing.JLabel ncar12;
    public static javax.swing.JLabel ncar13;
    public static javax.swing.JLabel ncar14;
    public static javax.swing.JLabel ncar15;
    public static javax.swing.JLabel ncar2;
    public static javax.swing.JLabel ncar3;
    public static javax.swing.JLabel ncar4;
    public static javax.swing.JLabel ncar5;
    public static javax.swing.JLabel ncar6;
    public static javax.swing.JLabel ncar7;
    public static javax.swing.JLabel ncar8;
    public static javax.swing.JLabel ncar9;
    // End of variables declaration//GEN-END:variables
}
