/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parking;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Mogith
 */
public class forgotpass extends javax.swing.JFrame {

    /**
     * Creates new form forgotpass
     */
    public forgotpass() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtuid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnewpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtoldpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtcnpass2 = new javax.swing.JPasswordField();
        ibuild = new javax.swing.JLabel();
        iboldpass = new javax.swing.JLabel();
        Iblcnfpass = new javax.swing.JLabel();
        clearbtn1 = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        btchangepass = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Change Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 24), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuidActionPerformed(evt);
            }
        });
        jPanel1.add(txtuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 39, 223, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NEW PASSWORD:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 195, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("USERID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 37, 71, 23));

        txtnewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewpassActionPerformed(evt);
            }
        });
        jPanel1.add(txtnewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 196, 223, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("OLD PASSWORD:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 116, 130, 20));
        jPanel1.add(txtoldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 117, 223, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CONFIRM PASSWORD:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 270, -1, 20));

        txtcnpass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnpass2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtcnpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 271, 223, 20));

        ibuild.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(ibuild, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 72, 187, 17));

        iboldpass.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(iboldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 155, 187, 17));

        Iblcnfpass.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(Iblcnfpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 303, 187, 20));

        clearbtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearbtn1.setText("clear");
        clearbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(clearbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 343, -1, -1));

        backbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backbtn.setText("back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 343, -1, -1));

        btchangepass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btchangepass.setText("change");
        btchangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btchangepassActionPerformed(evt);
            }
        });
        jPanel1.add(btchangepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 343, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 430, 340));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 230, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuidActionPerformed

    private void txtnewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewpassActionPerformed

    private void txtcnpass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnpass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnpass2ActionPerformed

    private void btchangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btchangepassActionPerformed
        // TODO add your handling code here:
        String uid,oldpass,newpass,cnfpass;
        uid = txtuid.getText();
        oldpass =txtoldpass.getText();
        newpass = txtnewpass.getText();
        cnfpass= txtcnpass2.getText();
        String r1 ="select * from login where username='"+uid+"'";
        String r2="update login set passwords='"+newpass+"'where username='"+uid+"' ";
        try{
            Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(r1);
            if(rs.next()){
              if(rs.getString("passwords").equals(oldpass)){
                 ibuild.setText("");
                 if(newpass.equals(cnfpass))
                 {
                     Iblcnfpass.setText("");
                     stmt.executeUpdate(r2);
                     JOptionPane.showMessageDialog(rootPane, "password change successfully:");
                 }
                 else
                 {
                     Iblcnfpass.setText("confirm password doesnot match");
                     txtcnpass2.requestFocus();
                 }
              }
              else
              {
                iboldpass.setText("Invalid old password");
                txtoldpass.requestFocus();
              }
            }
            else{
                ibuild.setText("Invalid user Id");
                txtuid.requestFocus();
            }
            txtuid.setText("");
            txtoldpass.setText("");
            txtnewpass.setText("");
            txtcnpass2.setText("");
        }
        catch (Exception e){
             System.out.println(e);
             e.printStackTrace();
           
        }
    }//GEN-LAST:event_btchangepassActionPerformed

    private void clearbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtn1ActionPerformed
        // TODO add your handling code here:
        txtuid.setText("");
        txtoldpass.setText("");
        txtnewpass.setText("");
        txtcnpass2.setText("");
        
    }//GEN-LAST:event_clearbtn1ActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        loginpage p;
        p=new loginpage();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new forgotpass().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Iblcnfpass;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btchangepass;
    private javax.swing.JButton clearbtn1;
    private javax.swing.JLabel iboldpass;
    private javax.swing.JLabel ibuild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txtcnpass2;
    private javax.swing.JPasswordField txtnewpass;
    private javax.swing.JPasswordField txtoldpass;
    private javax.swing.JTextField txtuid;
    // End of variables declaration//GEN-END:variables
}
