/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static parking.updateprofile.txtuser;

/**
 *
 * @author Mogith
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        profilebtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pick2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(678, 405));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("SIGN OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 110, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("BOOK SLOTS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 110, 50));

        profilebtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        profilebtn.setForeground(new java.awt.Color(153, 0, 0));
        profilebtn.setText("PROFILE");
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });
        jPanel2.add(profilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 300));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ONLINE PARKING SYSTEM");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 230, -1));

        pick2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/java-6.jpg"))); // NOI18N
        pick2.setText("jLabel3");
        jPanel3.add(pick2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 260, 220));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 290, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loginpage p = new loginpage();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebtnActionPerformed
        // TODO add your handling code here:
        updateprofile up = new updateprofile();
        up.setVisible(true);
        this.dispose();
        try{
            String t = loginpage.edtUsername.getText();
            txtuser.setText(t);
        String query1="select * from login where username='"+loginpage.edtUsername.getText()+"'";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while(rs.next()){
                String mail=  rs.getString("email");
               String num = rs.getString("numbers");
               String add = rs.getString("address"); 
               updateprofile.txtmail.setText(mail);
               updateprofile.txtnum.setText(num);
               updateprofile.txtadd.setText(add);
            }
            
        }
        catch (Exception e){
            e.printStackTrace();
    
        }
        
    }//GEN-LAST:event_profilebtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int count=0;
        try{
       String query2="select * from booking";
      
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query2);
            while(rs.next()){
                String name = rs.getString(1);
                if(name.equalsIgnoreCase(loginpage.edtUsername.getText())){
                    count++;
                }
                
            }
        }

        catch(Exception e){
            e.printStackTrace();
        }
       if(count!=1){
        booking b = new booking();
        b.setVisible(true);
        this.dispose();
        booking.car1.setVisible(false);
        booking.car2.setVisible(false);
        booking.car6.setVisible(false);
        booking.car4.setVisible(false);
        booking.car5.setVisible(false);
        booking.car6.setVisible(false);
        booking.car7.setVisible(false);
        booking.car8.setVisible(false);
        booking.car9.setVisible(false);
        booking.car10.setVisible(false);
        booking.car11.setVisible(false);
        booking.car12.setVisible(false);
        booking.car13.setVisible(false);
        booking.car14.setVisible(false);
        booking.car15.setVisible(false);
        try{
            String query1="select * from booking";
             Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            Statement stm=con.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            while (rs.next()){
                 String s = rs.getString("carnumber");
                 if(s.equals("scar1")){
                     booking.car1.setVisible(true);
                     booking.ncar1.setVisible(false);
                     //booking.car1.setEnabled(false);
              
                 }
                 else if(s.equals("scar2")){
                      booking.car2.setVisible(true);
                     booking.ncar2.setVisible(false);
                 }
                else if(s.equals("scar3")){
                      booking.car3.setVisible(true);
                     booking.ncar3.setVisible(false);
                 }
                 else if(s.equals("scar4")){
                      booking.car4.setVisible(true);
                     booking.ncar4.setVisible(false);
                 }
                 else if(s.equals("scar5")){
                      booking.car5.setVisible(true);
                     booking.ncar5.setVisible(false);
                 }
                 else if(s.equals("scar6")){
                      booking.car6.setVisible(true);
                     booking.ncar6.setVisible(false);
                 }
                 else if(s.equals("scar7")){
                      booking.car7.setVisible(true);
                     booking.ncar7.setVisible(false);
                 }
                 else if(s.equals("scar8")){
                      booking.car8.setVisible(true);
                     booking.ncar8.setVisible(false);
                 }
                 else if(s.equals("scar9")){
                      booking.car9.setVisible(true);
                     booking.ncar9.setVisible(false);
                 }
                 else if(s.equals("scar10")){
                      booking.car10.setVisible(true);
                     booking.ncar10.setVisible(false);
                 }
                 else if(s.equals("scar11")){
                      booking.car11.setVisible(true);
                     booking.ncar11.setVisible(false);
                 }
                 else if(s.equals("scar12")){
                      booking.car12.setVisible(true);
                     booking.ncar12.setVisible(false);
                 }
                 else if(s.equals("scar13")){
                      booking.car13.setVisible(true);
                     booking.ncar13.setVisible(false);
                 }
                 else if(s.equals("scar14")){
                      booking.car14.setVisible(true);
                     booking.ncar14.setVisible(false);
                 }
                 else if(s.equals("scar15")){
                      booking.car15.setVisible(true);
                     booking.ncar15.setVisible(false);
                 }
            }
        }
         catch(Exception e){
            e.printStackTrace();
        }
       }
       else{
           JOptionPane.showMessageDialog(null, "slot booked already", "",JOptionPane.ERROR_MESSAGE );
       }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new homepage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pick2;
    private javax.swing.JButton profilebtn;
    // End of variables declaration//GEN-END:variables
}
