/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parking;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Mogith
 */
public class signup extends javax.swing.JFrame {
    private String username;
    /**
     * Creates new form signup
     */
    public signup() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edtName = new javax.swing.JTextField();
        gendercb = new javax.swing.JComboBox<>();
        edtMail = new javax.swing.JTextField();
        edtPassword = new javax.swing.JTextField();
        edtcp = new javax.swing.JTextField();
        edtAddress = new javax.swing.JTextField();
        edtNumber = new javax.swing.JTextField();
        btnSingup = new javax.swing.JButton();

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 153));
        setFont(new java.awt.Font("Book Antiqua", 0, 10)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel1.setText("           NEW USER REGISTER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 6, 390, 41));

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclear.setText("clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 427, -1, -1));

        backbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 427, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("USERNAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 70, 71, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("GENDER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 118, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("EMAIL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 171, 71, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("PASSWORD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 214, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CONFIRM PASSWORD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 259, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("ADDRESS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 306, 62, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("MOBILE NO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 366, -1, -1));

        edtName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        edtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNameActionPerformed(evt);
            }
        });
        jPanel1.add(edtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 68, 104, -1));

        gendercb.setFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        gendercb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "_____select type_____", "male", "female", "other gender" }));
        gendercb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendercbActionPerformed(evt);
            }
        });
        jPanel1.add(gendercb, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 115, -1, -1));

        edtMail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        edtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtMailActionPerformed(evt);
            }
        });
        jPanel1.add(edtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 169, 160, -1));

        edtPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        edtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(edtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 214, 155, -1));

        edtcp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(edtcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 257, 150, -1));

        edtAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        edtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(edtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 295, 186, 40));

        edtNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        edtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNumberActionPerformed(evt);
            }
        });
        jPanel1.add(edtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 360, 186, 30));

        btnSingup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSingup.setText("Submit");
        btnSingup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingupActionPerformed(evt);
            }
        });
        jPanel1.add(btnSingup, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 427, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        edtName.setText("");
        edtPassword.setText("");
        edtAddress.setText("");
        edtNumber.setText("");
        edtMail.setText("");
        gendercb.setSelectedIndex(0);
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnSingupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingupActionPerformed
        // TODO add your handling code here:
        String tname = edtName.getText();
        String pass = edtPassword.getText();
        String add = edtAddress.getText();
        String mail = edtMail.getText();
        String gender=gendercb.getSelectedItem().toString();
        String conpass;
        conpass = edtcp.getText();
        
        String num=edtNumber.getText();
        int len=num.length();
        try{
            char[] chr = new char[mail.length()];
        mail.getChars(mail.length()-11,mail.length()-1,chr,0);
        String str = new String(chr);
        if(str.equalsIgnoreCase("@gmail.com"))
            {
                JOptionPane.showMessageDialog(edtNumber, "Enter a valid mail id");  
            }
        }
            catch(StringIndexOutOfBoundsException st){
                    JOptionPane.showMessageDialog(edtNumber, "Enter a valid mail id");
                    }
        try{
            Connection con;
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","21mis0204@siteora");
            String query = "insert into login (username,passwords,address,email,numbers,gender) values(?,?,?,?,?,?)";
            if (!edtPassword.getText(). equals (edtcp.getText())){
               JOptionPane.showMessageDialog(null,"password does not match","",JOptionPane.WARNING_MESSAGE);
        }
            else if(len!=10){
            JOptionPane.showMessageDialog(edtNumber, "Enter a valid mobile number");
            }
            else{
               PreparedStatement ps= con.prepareStatement(query);
            ps.setString(1,edtName.getText());
            ps.setString(2,edtPassword.getText());
            ps.setString(3,edtAddress.getText());
            ps.setString(4,edtMail.getText());
            ps.setString(5,edtNumber.getText());
            ps.setString(6, (String) gendercb.getSelectedItem());
            ps.executeUpdate();
            }  
        edtName.setText("");
        edtPassword.setText("");
        edtAddress.setText("");
        edtNumber.setText("");
        edtMail.setText("");
        gendercb.setSelectedIndex(0);
        edtcp.setText("");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSingupActionPerformed

    private void edtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNumberActionPerformed

    private void edtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtAddressActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void edtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNameActionPerformed

    private void edtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtMailActionPerformed

    private void edtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPasswordActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        loginpage s;
        s = new loginpage();
        s.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void gendercbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendercbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gendercbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSingup;
    private javax.swing.JButton btnclear;
    private javax.swing.JTextField edtAddress;
    private javax.swing.JTextField edtMail;
    private javax.swing.JTextField edtName;
    private javax.swing.JTextField edtNumber;
    private javax.swing.JTextField edtPassword;
    private javax.swing.JTextField edtcp;
    private javax.swing.JComboBox<String> gendercb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
